//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Library.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Transaction
    {
        public int TransactionId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> BookId { get; set; }
        public System.DateTime IssueDate { get; set; }
        public System.DateTime DueDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
    
        public virtual tbl_Books tbl_Books { get; set; }
        public virtual tbl_Users tbl_Users { get; set; }
    }
}
