//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Library.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Role
    {
        public tbl_Role()
        {
            this.tbl_Users = new HashSet<tbl_Users>();
        }
    
        public int RoleId { get; set; }
        public string Role { get; set; }
    
        public virtual ICollection<tbl_Users> tbl_Users { get; set; }
    }
}
