//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Library.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Users
    {
        public tbl_Users()
        {
            this.tbl_Transaction = new HashSet<tbl_Transaction>();
        }
    
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }
        public System.DateTime DOB { get; set; }
        public string MobileNo { get; set; }
        public string EmailId { get; set; }
        public Nullable<int> RoleId { get; set; }
    
        public virtual tbl_Role tbl_Role { get; set; }
        public virtual ICollection<tbl_Transaction> tbl_Transaction { get; set; }
    }
}
