//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.LibraryServiceClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Books", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Library.WCFService.Service")]
    [System.SerializableAttribute()]
    public partial class Books : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> AvailStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BookIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISBNNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublisherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> AvailStatus {
            get {
                return this.AvailStatusField;
            }
            set {
                if ((this.AvailStatusField.Equals(value) != true)) {
                    this.AvailStatusField = value;
                    this.RaisePropertyChanged("AvailStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BookId {
            get {
                return this.BookIdField;
            }
            set {
                if ((this.BookIdField.Equals(value) != true)) {
                    this.BookIdField = value;
                    this.RaisePropertyChanged("BookId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISBNNumber {
            get {
                return this.ISBNNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ISBNNumberField, value) != true)) {
                    this.ISBNNumberField = value;
                    this.RaisePropertyChanged("ISBNNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Publisher {
            get {
                return this.PublisherField;
            }
            set {
                if ((object.ReferenceEquals(this.PublisherField, value) != true)) {
                    this.PublisherField = value;
                    this.RaisePropertyChanged("Publisher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Categories", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Library.WCFService.Service")]
    [System.SerializableAttribute()]
    public partial class Categories : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((this.CategoryIdField.Equals(value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Users", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Library.WCFService.Service")]
    [System.SerializableAttribute()]
    public partial class Users : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DOBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RoleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DOB {
            get {
                return this.DOBField;
            }
            set {
                if ((this.DOBField.Equals(value) != true)) {
                    this.DOBField = value;
                    this.RaisePropertyChanged("DOB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailId {
            get {
                return this.EmailIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailIdField, value) != true)) {
                    this.EmailIdField = value;
                    this.RaisePropertyChanged("EmailId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNo {
            get {
                return this.MobileNoField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileNoField, value) != true)) {
                    this.MobileNoField = value;
                    this.RaisePropertyChanged("MobileNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RoleId {
            get {
                return this.RoleIdField;
            }
            set {
                if ((this.RoleIdField.Equals(value) != true)) {
                    this.RoleIdField = value;
                    this.RaisePropertyChanged("RoleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transaction", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Library.WCFService.Service")]
    [System.SerializableAttribute()]
    public partial class Transaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BookIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime IssueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ReturnDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TransactionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.LibraryServiceClient.tbl_Books tbl_BooksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.LibraryServiceClient.tbl_Users tbl_UsersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BookId {
            get {
                return this.BookIdField;
            }
            set {
                if ((this.BookIdField.Equals(value) != true)) {
                    this.BookIdField = value;
                    this.RaisePropertyChanged("BookId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DueDate {
            get {
                return this.DueDateField;
            }
            set {
                if ((this.DueDateField.Equals(value) != true)) {
                    this.DueDateField = value;
                    this.RaisePropertyChanged("DueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime IssueDate {
            get {
                return this.IssueDateField;
            }
            set {
                if ((this.IssueDateField.Equals(value) != true)) {
                    this.IssueDateField = value;
                    this.RaisePropertyChanged("IssueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ReturnDate {
            get {
                return this.ReturnDateField;
            }
            set {
                if ((this.ReturnDateField.Equals(value) != true)) {
                    this.ReturnDateField = value;
                    this.RaisePropertyChanged("ReturnDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TransactionId {
            get {
                return this.TransactionIdField;
            }
            set {
                if ((this.TransactionIdField.Equals(value) != true)) {
                    this.TransactionIdField = value;
                    this.RaisePropertyChanged("TransactionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.LibraryServiceClient.tbl_Books tbl_Books {
            get {
                return this.tbl_BooksField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_BooksField, value) != true)) {
                    this.tbl_BooksField = value;
                    this.RaisePropertyChanged("tbl_Books");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.LibraryServiceClient.tbl_Users tbl_Users {
            get {
                return this.tbl_UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_UsersField, value) != true)) {
                    this.tbl_UsersField = value;
                    this.RaisePropertyChanged("tbl_Users");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_Books", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Library.Core.Model")]
    [System.SerializableAttribute()]
    public partial class tbl_Books : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> AvailStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BookIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISBNNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublisherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.LibraryServiceClient.tbl_Transaction[] tbl_TransactionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> AvailStatus {
            get {
                return this.AvailStatusField;
            }
            set {
                if ((this.AvailStatusField.Equals(value) != true)) {
                    this.AvailStatusField = value;
                    this.RaisePropertyChanged("AvailStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BookId {
            get {
                return this.BookIdField;
            }
            set {
                if ((this.BookIdField.Equals(value) != true)) {
                    this.BookIdField = value;
                    this.RaisePropertyChanged("BookId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISBNNumber {
            get {
                return this.ISBNNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ISBNNumberField, value) != true)) {
                    this.ISBNNumberField = value;
                    this.RaisePropertyChanged("ISBNNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Publisher {
            get {
                return this.PublisherField;
            }
            set {
                if ((object.ReferenceEquals(this.PublisherField, value) != true)) {
                    this.PublisherField = value;
                    this.RaisePropertyChanged("Publisher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.LibraryServiceClient.tbl_Transaction[] tbl_Transaction {
            get {
                return this.tbl_TransactionField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_TransactionField, value) != true)) {
                    this.tbl_TransactionField = value;
                    this.RaisePropertyChanged("tbl_Transaction");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_Users", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Library.Core.Model")]
    [System.SerializableAttribute()]
    public partial class tbl_Users : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DOBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RoleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.LibraryServiceClient.tbl_Role tbl_RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.LibraryServiceClient.tbl_Transaction[] tbl_TransactionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DOB {
            get {
                return this.DOBField;
            }
            set {
                if ((this.DOBField.Equals(value) != true)) {
                    this.DOBField = value;
                    this.RaisePropertyChanged("DOB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailId {
            get {
                return this.EmailIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailIdField, value) != true)) {
                    this.EmailIdField = value;
                    this.RaisePropertyChanged("EmailId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNo {
            get {
                return this.MobileNoField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileNoField, value) != true)) {
                    this.MobileNoField = value;
                    this.RaisePropertyChanged("MobileNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RoleId {
            get {
                return this.RoleIdField;
            }
            set {
                if ((this.RoleIdField.Equals(value) != true)) {
                    this.RoleIdField = value;
                    this.RaisePropertyChanged("RoleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.LibraryServiceClient.tbl_Role tbl_Role {
            get {
                return this.tbl_RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_RoleField, value) != true)) {
                    this.tbl_RoleField = value;
                    this.RaisePropertyChanged("tbl_Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.LibraryServiceClient.tbl_Transaction[] tbl_Transaction {
            get {
                return this.tbl_TransactionField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_TransactionField, value) != true)) {
                    this.tbl_TransactionField = value;
                    this.RaisePropertyChanged("tbl_Transaction");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_Transaction", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Library.Core.Model")]
    [System.SerializableAttribute()]
    public partial class tbl_Transaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BookIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime IssueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ReturnDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TransactionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.LibraryServiceClient.tbl_Books tbl_BooksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.LibraryServiceClient.tbl_Users tbl_UsersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BookId {
            get {
                return this.BookIdField;
            }
            set {
                if ((this.BookIdField.Equals(value) != true)) {
                    this.BookIdField = value;
                    this.RaisePropertyChanged("BookId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DueDate {
            get {
                return this.DueDateField;
            }
            set {
                if ((this.DueDateField.Equals(value) != true)) {
                    this.DueDateField = value;
                    this.RaisePropertyChanged("DueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime IssueDate {
            get {
                return this.IssueDateField;
            }
            set {
                if ((this.IssueDateField.Equals(value) != true)) {
                    this.IssueDateField = value;
                    this.RaisePropertyChanged("IssueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ReturnDate {
            get {
                return this.ReturnDateField;
            }
            set {
                if ((this.ReturnDateField.Equals(value) != true)) {
                    this.ReturnDateField = value;
                    this.RaisePropertyChanged("ReturnDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TransactionId {
            get {
                return this.TransactionIdField;
            }
            set {
                if ((this.TransactionIdField.Equals(value) != true)) {
                    this.TransactionIdField = value;
                    this.RaisePropertyChanged("TransactionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.LibraryServiceClient.tbl_Books tbl_Books {
            get {
                return this.tbl_BooksField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_BooksField, value) != true)) {
                    this.tbl_BooksField = value;
                    this.RaisePropertyChanged("tbl_Books");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.LibraryServiceClient.tbl_Users tbl_Users {
            get {
                return this.tbl_UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_UsersField, value) != true)) {
                    this.tbl_UsersField = value;
                    this.RaisePropertyChanged("tbl_Users");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_Role", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Library.Core.Model")]
    [System.SerializableAttribute()]
    public partial class tbl_Role : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.LibraryServiceClient.tbl_Users[] tbl_UsersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoleId {
            get {
                return this.RoleIdField;
            }
            set {
                if ((this.RoleIdField.Equals(value) != true)) {
                    this.RoleIdField = value;
                    this.RaisePropertyChanged("RoleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.LibraryServiceClient.tbl_Users[] tbl_Users {
            get {
                return this.tbl_UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_UsersField, value) != true)) {
                    this.tbl_UsersField = value;
                    this.RaisePropertyChanged("tbl_Users");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LibraryServiceClient.ILibraryService")]
    public interface ILibraryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/AddBook", ReplyAction="http://tempuri.org/ILibraryService/AddBookResponse")]
        int AddBook(WebApplication1.LibraryServiceClient.Books books);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/AddBook", ReplyAction="http://tempuri.org/ILibraryService/AddBookResponse")]
        System.Threading.Tasks.Task<int> AddBookAsync(WebApplication1.LibraryServiceClient.Books books);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/AddCategory", ReplyAction="http://tempuri.org/ILibraryService/AddCategoryResponse")]
        int AddCategory([System.ServiceModel.MessageParameterAttribute(Name="addcategory")] WebApplication1.LibraryServiceClient.Categories addcategory1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/AddCategory", ReplyAction="http://tempuri.org/ILibraryService/AddCategoryResponse")]
        System.Threading.Tasks.Task<int> AddCategoryAsync(WebApplication1.LibraryServiceClient.Categories addcategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/AddMember", ReplyAction="http://tempuri.org/ILibraryService/AddMemberResponse")]
        int AddMember(WebApplication1.LibraryServiceClient.Users users);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/AddMember", ReplyAction="http://tempuri.org/ILibraryService/AddMemberResponse")]
        System.Threading.Tasks.Task<int> AddMemberAsync(WebApplication1.LibraryServiceClient.Users users);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/UpdateBook", ReplyAction="http://tempuri.org/ILibraryService/UpdateBookResponse")]
        int UpdateBook(WebApplication1.LibraryServiceClient.Books books);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/UpdateBook", ReplyAction="http://tempuri.org/ILibraryService/UpdateBookResponse")]
        System.Threading.Tasks.Task<int> UpdateBookAsync(WebApplication1.LibraryServiceClient.Books books);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/UpdateMemberDetails", ReplyAction="http://tempuri.org/ILibraryService/UpdateMemberDetailsResponse")]
        int UpdateMemberDetails(WebApplication1.LibraryServiceClient.Users users);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/UpdateMemberDetails", ReplyAction="http://tempuri.org/ILibraryService/UpdateMemberDetailsResponse")]
        System.Threading.Tasks.Task<int> UpdateMemberDetailsAsync(WebApplication1.LibraryServiceClient.Users users);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/DeleteMember", ReplyAction="http://tempuri.org/ILibraryService/DeleteMemberResponse")]
        int DeleteMember(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/DeleteMember", ReplyAction="http://tempuri.org/ILibraryService/DeleteMemberResponse")]
        System.Threading.Tasks.Task<int> DeleteMemberAsync(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/DeleteBook", ReplyAction="http://tempuri.org/ILibraryService/DeleteBookResponse")]
        int DeleteBook(int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/DeleteBook", ReplyAction="http://tempuri.org/ILibraryService/DeleteBookResponse")]
        System.Threading.Tasks.Task<int> DeleteBookAsync(int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/GetAllCategories", ReplyAction="http://tempuri.org/ILibraryService/GetAllCategoriesResponse")]
        WebApplication1.LibraryServiceClient.Categories[] GetAllCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/GetAllCategories", ReplyAction="http://tempuri.org/ILibraryService/GetAllCategoriesResponse")]
        System.Threading.Tasks.Task<WebApplication1.LibraryServiceClient.Categories[]> GetAllCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/GetAllTransaction", ReplyAction="http://tempuri.org/ILibraryService/GetAllTransactionResponse")]
        WebApplication1.LibraryServiceClient.Transaction[] GetAllTransaction();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/GetAllTransaction", ReplyAction="http://tempuri.org/ILibraryService/GetAllTransactionResponse")]
        System.Threading.Tasks.Task<WebApplication1.LibraryServiceClient.Transaction[]> GetAllTransactionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/GetBookDetails", ReplyAction="http://tempuri.org/ILibraryService/GetBookDetailsResponse")]
        WebApplication1.LibraryServiceClient.Books GetBookDetails(int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/GetBookDetails", ReplyAction="http://tempuri.org/ILibraryService/GetBookDetailsResponse")]
        System.Threading.Tasks.Task<WebApplication1.LibraryServiceClient.Books> GetBookDetailsAsync(int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/GetMemberDetails", ReplyAction="http://tempuri.org/ILibraryService/GetMemberDetailsResponse")]
        WebApplication1.LibraryServiceClient.Users GetMemberDetails(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/GetMemberDetails", ReplyAction="http://tempuri.org/ILibraryService/GetMemberDetailsResponse")]
        System.Threading.Tasks.Task<WebApplication1.LibraryServiceClient.Users> GetMemberDetailsAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/GetReturnDetails", ReplyAction="http://tempuri.org/ILibraryService/GetReturnDetailsResponse")]
        WebApplication1.LibraryServiceClient.Transaction GetReturnDetails(int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/GetReturnDetails", ReplyAction="http://tempuri.org/ILibraryService/GetReturnDetailsResponse")]
        System.Threading.Tasks.Task<WebApplication1.LibraryServiceClient.Transaction> GetReturnDetailsAsync(int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/GetSelfTransaction", ReplyAction="http://tempuri.org/ILibraryService/GetSelfTransactionResponse")]
        WebApplication1.LibraryServiceClient.Transaction[] GetSelfTransaction(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/GetSelfTransaction", ReplyAction="http://tempuri.org/ILibraryService/GetSelfTransactionResponse")]
        System.Threading.Tasks.Task<WebApplication1.LibraryServiceClient.Transaction[]> GetSelfTransactionAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/SearchBooks", ReplyAction="http://tempuri.org/ILibraryService/SearchBooksResponse")]
        WebApplication1.LibraryServiceClient.Books[] SearchBooks(string columnName, string searchItems);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/SearchBooks", ReplyAction="http://tempuri.org/ILibraryService/SearchBooksResponse")]
        System.Threading.Tasks.Task<WebApplication1.LibraryServiceClient.Books[]> SearchBooksAsync(string columnName, string searchItems);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/CheckMemberAvlblty", ReplyAction="http://tempuri.org/ILibraryService/CheckMemberAvlbltyResponse")]
        int CheckMemberAvlblty(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/CheckMemberAvlblty", ReplyAction="http://tempuri.org/ILibraryService/CheckMemberAvlbltyResponse")]
        System.Threading.Tasks.Task<int> CheckMemberAvlbltyAsync(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/CheckMemberAvailability", ReplyAction="http://tempuri.org/ILibraryService/CheckMemberAvailabilityResponse")]
        int CheckMemberAvailability(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/CheckMemberAvailability", ReplyAction="http://tempuri.org/ILibraryService/CheckMemberAvailabilityResponse")]
        System.Threading.Tasks.Task<int> CheckMemberAvailabilityAsync(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/CheckBookAvailibility", ReplyAction="http://tempuri.org/ILibraryService/CheckBookAvailibilityResponse")]
        int CheckBookAvailibility(int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/CheckBookAvailibility", ReplyAction="http://tempuri.org/ILibraryService/CheckBookAvailibilityResponse")]
        System.Threading.Tasks.Task<int> CheckBookAvailibilityAsync(int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/CheckBookAvlblty", ReplyAction="http://tempuri.org/ILibraryService/CheckBookAvlbltyResponse")]
        int CheckBookAvlblty(int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/CheckBookAvlblty", ReplyAction="http://tempuri.org/ILibraryService/CheckBookAvlbltyResponse")]
        System.Threading.Tasks.Task<int> CheckBookAvlbltyAsync(int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/CheckBookAvlbltyIssue", ReplyAction="http://tempuri.org/ILibraryService/CheckBookAvlbltyIssueResponse")]
        int CheckBookAvlbltyIssue(int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/CheckBookAvlbltyIssue", ReplyAction="http://tempuri.org/ILibraryService/CheckBookAvlbltyIssueResponse")]
        System.Threading.Tasks.Task<int> CheckBookAvlbltyIssueAsync(int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/IssueBook", ReplyAction="http://tempuri.org/ILibraryService/IssueBookResponse")]
        int IssueBook(WebApplication1.LibraryServiceClient.Transaction issue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/IssueBook", ReplyAction="http://tempuri.org/ILibraryService/IssueBookResponse")]
        System.Threading.Tasks.Task<int> IssueBookAsync(WebApplication1.LibraryServiceClient.Transaction issue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/ReturnBook", ReplyAction="http://tempuri.org/ILibraryService/ReturnBookResponse")]
        int ReturnBook([System.ServiceModel.MessageParameterAttribute(Name="returnBook")] WebApplication1.LibraryServiceClient.Transaction returnBook1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/ReturnBook", ReplyAction="http://tempuri.org/ILibraryService/ReturnBookResponse")]
        System.Threading.Tasks.Task<int> ReturnBookAsync(WebApplication1.LibraryServiceClient.Transaction returnBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/Login", ReplyAction="http://tempuri.org/ILibraryService/LoginResponse")]
        WebApplication1.LibraryServiceClient.Users Login(int userId, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/Login", ReplyAction="http://tempuri.org/ILibraryService/LoginResponse")]
        System.Threading.Tasks.Task<WebApplication1.LibraryServiceClient.Users> LoginAsync(int userId, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/GetAuthenticationDetails", ReplyAction="http://tempuri.org/ILibraryService/GetAuthenticationDetailsResponse")]
        WebApplication1.LibraryServiceClient.Users GetAuthenticationDetails(string emailId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryService/GetAuthenticationDetails", ReplyAction="http://tempuri.org/ILibraryService/GetAuthenticationDetailsResponse")]
        System.Threading.Tasks.Task<WebApplication1.LibraryServiceClient.Users> GetAuthenticationDetailsAsync(string emailId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILibraryServiceChannel : WebApplication1.LibraryServiceClient.ILibraryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LibraryServiceClient : System.ServiceModel.ClientBase<WebApplication1.LibraryServiceClient.ILibraryService>, WebApplication1.LibraryServiceClient.ILibraryService {
        
        public LibraryServiceClient() {
        }
        
        public LibraryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LibraryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibraryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibraryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddBook(WebApplication1.LibraryServiceClient.Books books) {
            return base.Channel.AddBook(books);
        }
        
        public System.Threading.Tasks.Task<int> AddBookAsync(WebApplication1.LibraryServiceClient.Books books) {
            return base.Channel.AddBookAsync(books);
        }
        
        public int AddCategory(WebApplication1.LibraryServiceClient.Categories addcategory1) {
            return base.Channel.AddCategory(addcategory1);
        }
        
        public System.Threading.Tasks.Task<int> AddCategoryAsync(WebApplication1.LibraryServiceClient.Categories addcategory) {
            return base.Channel.AddCategoryAsync(addcategory);
        }
        
        public int AddMember(WebApplication1.LibraryServiceClient.Users users) {
            return base.Channel.AddMember(users);
        }
        
        public System.Threading.Tasks.Task<int> AddMemberAsync(WebApplication1.LibraryServiceClient.Users users) {
            return base.Channel.AddMemberAsync(users);
        }
        
        public int UpdateBook(WebApplication1.LibraryServiceClient.Books books) {
            return base.Channel.UpdateBook(books);
        }
        
        public System.Threading.Tasks.Task<int> UpdateBookAsync(WebApplication1.LibraryServiceClient.Books books) {
            return base.Channel.UpdateBookAsync(books);
        }
        
        public int UpdateMemberDetails(WebApplication1.LibraryServiceClient.Users users) {
            return base.Channel.UpdateMemberDetails(users);
        }
        
        public System.Threading.Tasks.Task<int> UpdateMemberDetailsAsync(WebApplication1.LibraryServiceClient.Users users) {
            return base.Channel.UpdateMemberDetailsAsync(users);
        }
        
        public int DeleteMember(int userID) {
            return base.Channel.DeleteMember(userID);
        }
        
        public System.Threading.Tasks.Task<int> DeleteMemberAsync(int userID) {
            return base.Channel.DeleteMemberAsync(userID);
        }
        
        public int DeleteBook(int bookId) {
            return base.Channel.DeleteBook(bookId);
        }
        
        public System.Threading.Tasks.Task<int> DeleteBookAsync(int bookId) {
            return base.Channel.DeleteBookAsync(bookId);
        }
        
        public WebApplication1.LibraryServiceClient.Categories[] GetAllCategories() {
            return base.Channel.GetAllCategories();
        }
        
        public System.Threading.Tasks.Task<WebApplication1.LibraryServiceClient.Categories[]> GetAllCategoriesAsync() {
            return base.Channel.GetAllCategoriesAsync();
        }
        
        public WebApplication1.LibraryServiceClient.Transaction[] GetAllTransaction() {
            return base.Channel.GetAllTransaction();
        }
        
        public System.Threading.Tasks.Task<WebApplication1.LibraryServiceClient.Transaction[]> GetAllTransactionAsync() {
            return base.Channel.GetAllTransactionAsync();
        }
        
        public WebApplication1.LibraryServiceClient.Books GetBookDetails(int bookId) {
            return base.Channel.GetBookDetails(bookId);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.LibraryServiceClient.Books> GetBookDetailsAsync(int bookId) {
            return base.Channel.GetBookDetailsAsync(bookId);
        }
        
        public WebApplication1.LibraryServiceClient.Users GetMemberDetails(int userId) {
            return base.Channel.GetMemberDetails(userId);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.LibraryServiceClient.Users> GetMemberDetailsAsync(int userId) {
            return base.Channel.GetMemberDetailsAsync(userId);
        }
        
        public WebApplication1.LibraryServiceClient.Transaction GetReturnDetails(int bookId) {
            return base.Channel.GetReturnDetails(bookId);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.LibraryServiceClient.Transaction> GetReturnDetailsAsync(int bookId) {
            return base.Channel.GetReturnDetailsAsync(bookId);
        }
        
        public WebApplication1.LibraryServiceClient.Transaction[] GetSelfTransaction(int userId) {
            return base.Channel.GetSelfTransaction(userId);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.LibraryServiceClient.Transaction[]> GetSelfTransactionAsync(int userId) {
            return base.Channel.GetSelfTransactionAsync(userId);
        }
        
        public WebApplication1.LibraryServiceClient.Books[] SearchBooks(string columnName, string searchItems) {
            return base.Channel.SearchBooks(columnName, searchItems);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.LibraryServiceClient.Books[]> SearchBooksAsync(string columnName, string searchItems) {
            return base.Channel.SearchBooksAsync(columnName, searchItems);
        }
        
        public int CheckMemberAvlblty(int userID) {
            return base.Channel.CheckMemberAvlblty(userID);
        }
        
        public System.Threading.Tasks.Task<int> CheckMemberAvlbltyAsync(int userID) {
            return base.Channel.CheckMemberAvlbltyAsync(userID);
        }
        
        public int CheckMemberAvailability(int userID) {
            return base.Channel.CheckMemberAvailability(userID);
        }
        
        public System.Threading.Tasks.Task<int> CheckMemberAvailabilityAsync(int userID) {
            return base.Channel.CheckMemberAvailabilityAsync(userID);
        }
        
        public int CheckBookAvailibility(int bookId) {
            return base.Channel.CheckBookAvailibility(bookId);
        }
        
        public System.Threading.Tasks.Task<int> CheckBookAvailibilityAsync(int bookId) {
            return base.Channel.CheckBookAvailibilityAsync(bookId);
        }
        
        public int CheckBookAvlblty(int bookId) {
            return base.Channel.CheckBookAvlblty(bookId);
        }
        
        public System.Threading.Tasks.Task<int> CheckBookAvlbltyAsync(int bookId) {
            return base.Channel.CheckBookAvlbltyAsync(bookId);
        }
        
        public int CheckBookAvlbltyIssue(int bookId) {
            return base.Channel.CheckBookAvlbltyIssue(bookId);
        }
        
        public System.Threading.Tasks.Task<int> CheckBookAvlbltyIssueAsync(int bookId) {
            return base.Channel.CheckBookAvlbltyIssueAsync(bookId);
        }
        
        public int IssueBook(WebApplication1.LibraryServiceClient.Transaction issue) {
            return base.Channel.IssueBook(issue);
        }
        
        public System.Threading.Tasks.Task<int> IssueBookAsync(WebApplication1.LibraryServiceClient.Transaction issue) {
            return base.Channel.IssueBookAsync(issue);
        }
        
        public int ReturnBook(WebApplication1.LibraryServiceClient.Transaction returnBook1) {
            return base.Channel.ReturnBook(returnBook1);
        }
        
        public System.Threading.Tasks.Task<int> ReturnBookAsync(WebApplication1.LibraryServiceClient.Transaction returnBook) {
            return base.Channel.ReturnBookAsync(returnBook);
        }
        
        public WebApplication1.LibraryServiceClient.Users Login(int userId, string password) {
            return base.Channel.Login(userId, password);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.LibraryServiceClient.Users> LoginAsync(int userId, string password) {
            return base.Channel.LoginAsync(userId, password);
        }
        
        public WebApplication1.LibraryServiceClient.Users GetAuthenticationDetails(string emailId) {
            return base.Channel.GetAuthenticationDetails(emailId);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.LibraryServiceClient.Users> GetAuthenticationDetailsAsync(string emailId) {
            return base.Channel.GetAuthenticationDetailsAsync(emailId);
        }
    }
}
